"""add deleted_at to files

Revision ID: 19857e9f0f79
Revises: 88d71d8ab6c0
Create Date: 2026-06-08 18:43:27.527345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19857e9f0f79'
down_revision: Union[str, Sequence[str], None] = '88d71d8ab6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'deleted_at')
    # ### end Alembic commands ###
