"""add checksum to files

Revision ID: 7c0fbe25c14a
Revises: 67a38d07c6ce
Create Date: 2026-06-08 17:53:54.330263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0fbe25c14a'
down_revision: Union[str, Sequence[str], None] = '67a38d07c6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('files', sa.Column('checksum', sa.String(), nullable=True))
    # backfill existing rows
    op.execute("UPDATE files SET checksum = 'legacy' WHERE checksum IS NULL")
    # now make it NOT NULL
    op.alter_column('files', 'checksum', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'checksum')
    # ### end Alembic commands ###
