"""add permanent delete state

Revision ID: dfc82d7977f4
Revises: 19857e9f0f79
Create Date: 2026-06-08 20:06:58.723300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc82d7977f4'
down_revision: Union[str, Sequence[str], None] = '19857e9f0f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('files', sa.Column(
        'is_permanent_delete', 
        sa.Boolean(), 
        nullable=False,
        server_default='false'
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_permanent_delete')
    # ### end Alembic commands ###
